// Generated by rstantools.  Do not edit by hand.

/*
    ModStan is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    ModStan is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with ModStan.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#include <rstan/rstaninc.hpp>
// Code generated by Stan version 2.19.1
#include <stan/model/model_header.hpp>
namespace model_Pooling_namespace {
using std::istream;
using std::string;
using std::stringstream;
using std::vector;
using stan::io::dump;
using stan::math::lgamma;
using stan::model::prob_grad;
using namespace stan::math;
static int current_statement_begin__;
stan::io::program_reader prog_reader__() {
    stan::io::program_reader reader;
    reader.add_event(0, 0, "start", "model_Pooling");
    reader.add_event(76, 74, "end", "model_Pooling");
    return reader;
}
#include <stan_meta_header.hpp>
class model_Pooling : public prob_grad {
private:
        int N_obs;
        int N_pred;
        std::vector<double> resp;
        std::vector<double> dose;
        double maxdose;
        std::vector<double> Pred_doses;
        double prior_stdev_sigma;
public:
    model_Pooling(stan::io::var_context& context__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, 0, pstream__);
    }
    model_Pooling(stan::io::var_context& context__,
        unsigned int random_seed__,
        std::ostream* pstream__ = 0)
        : prob_grad(0) {
        ctor_body(context__, random_seed__, pstream__);
    }
    void ctor_body(stan::io::var_context& context__,
                   unsigned int random_seed__,
                   std::ostream* pstream__) {
        typedef double local_scalar_t__;
        boost::ecuyer1988 base_rng__ =
          stan::services::util::create_rng(random_seed__, 0);
        (void) base_rng__;  // suppress unused var warning
        current_statement_begin__ = -1;
        static const char* function__ = "model_Pooling_namespace::model_Pooling";
        (void) function__;  // dummy to suppress unused var warning
        size_t pos__;
        (void) pos__;  // dummy to suppress unused var warning
        std::vector<int> vals_i__;
        std::vector<double> vals_r__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        try {
            // initialize data block variables from context__
            current_statement_begin__ = 8;
            context__.validate_dims("data initialization", "N_obs", "int", context__.to_vec());
            N_obs = int(0);
            vals_i__ = context__.vals_i("N_obs");
            pos__ = 0;
            N_obs = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_obs", N_obs, 1);
            current_statement_begin__ = 9;
            context__.validate_dims("data initialization", "N_pred", "int", context__.to_vec());
            N_pred = int(0);
            vals_i__ = context__.vals_i("N_pred");
            pos__ = 0;
            N_pred = vals_i__[pos__++];
            check_greater_or_equal(function__, "N_pred", N_pred, 1);
            current_statement_begin__ = 10;
            validate_non_negative_index("resp", "N_obs", N_obs);
            context__.validate_dims("data initialization", "resp", "double", context__.to_vec(N_obs));
            resp = std::vector<double>(N_obs, double(0));
            vals_r__ = context__.vals_r("resp");
            pos__ = 0;
            size_t resp_k_0_max__ = N_obs;
            for (size_t k_0__ = 0; k_0__ < resp_k_0_max__; ++k_0__) {
                resp[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 11;
            validate_non_negative_index("dose", "N_obs", N_obs);
            context__.validate_dims("data initialization", "dose", "double", context__.to_vec(N_obs));
            dose = std::vector<double>(N_obs, double(0));
            vals_r__ = context__.vals_r("dose");
            pos__ = 0;
            size_t dose_k_0_max__ = N_obs;
            for (size_t k_0__ = 0; k_0__ < dose_k_0_max__; ++k_0__) {
                dose[k_0__] = vals_r__[pos__++];
            }
            size_t dose_i_0_max__ = N_obs;
            for (size_t i_0__ = 0; i_0__ < dose_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "dose[i_0__]", dose[i_0__], 0);
            }
            current_statement_begin__ = 12;
            context__.validate_dims("data initialization", "maxdose", "double", context__.to_vec());
            maxdose = double(0);
            vals_r__ = context__.vals_r("maxdose");
            pos__ = 0;
            maxdose = vals_r__[pos__++];
            check_greater_or_equal(function__, "maxdose", maxdose, 0);
            current_statement_begin__ = 13;
            validate_non_negative_index("Pred_doses", "N_pred", N_pred);
            context__.validate_dims("data initialization", "Pred_doses", "double", context__.to_vec(N_pred));
            Pred_doses = std::vector<double>(N_pred, double(0));
            vals_r__ = context__.vals_r("Pred_doses");
            pos__ = 0;
            size_t Pred_doses_k_0_max__ = N_pred;
            for (size_t k_0__ = 0; k_0__ < Pred_doses_k_0_max__; ++k_0__) {
                Pred_doses[k_0__] = vals_r__[pos__++];
            }
            current_statement_begin__ = 14;
            context__.validate_dims("data initialization", "prior_stdev_sigma", "double", context__.to_vec());
            prior_stdev_sigma = double(0);
            vals_r__ = context__.vals_r("prior_stdev_sigma");
            pos__ = 0;
            prior_stdev_sigma = vals_r__[pos__++];
            check_greater_or_equal(function__, "prior_stdev_sigma", prior_stdev_sigma, 0);
            // initialize transformed data variables
            // execute transformed data statements
            // validate transformed data
            // validate, set parameter ranges
            num_params_r__ = 0U;
            param_ranges_i__.clear();
            current_statement_begin__ = 18;
            num_params_r__ += 1;
            current_statement_begin__ = 19;
            num_params_r__ += 1;
            current_statement_begin__ = 20;
            num_params_r__ += 1;
            current_statement_begin__ = 21;
            num_params_r__ += 1;
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    ~model_Pooling() { }
    void transform_inits(const stan::io::var_context& context__,
                         std::vector<int>& params_i__,
                         std::vector<double>& params_r__,
                         std::ostream* pstream__) const {
        typedef double local_scalar_t__;
        stan::io::writer<double> writer__(params_r__, params_i__);
        size_t pos__;
        (void) pos__; // dummy call to supress warning
        std::vector<double> vals_r__;
        std::vector<int> vals_i__;
        current_statement_begin__ = 18;
        if (!(context__.contains_r("theta_0")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_0 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_0");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "theta_0", "double", context__.to_vec());
        double theta_0(0);
        theta_0 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(theta_0);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_0: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 19;
        if (!(context__.contains_r("theta_1")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_1 missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_1");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "theta_1", "double", context__.to_vec());
        double theta_1(0);
        theta_1 = vals_r__[pos__++];
        try {
            writer__.scalar_unconstrain(theta_1);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_1: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 20;
        if (!(context__.contains_r("theta_2_raw")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable theta_2_raw missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("theta_2_raw");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "theta_2_raw", "double", context__.to_vec());
        double theta_2_raw(0);
        theta_2_raw = vals_r__[pos__++];
        try {
            writer__.scalar_lub_unconstrain(0, 1.5, theta_2_raw);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable theta_2_raw: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        current_statement_begin__ = 21;
        if (!(context__.contains_r("sigma")))
            stan::lang::rethrow_located(std::runtime_error(std::string("Variable sigma missing")), current_statement_begin__, prog_reader__());
        vals_r__ = context__.vals_r("sigma");
        pos__ = 0U;
        context__.validate_dims("parameter initialization", "sigma", "double", context__.to_vec());
        double sigma(0);
        sigma = vals_r__[pos__++];
        try {
            writer__.scalar_lb_unconstrain(0, sigma);
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(std::runtime_error(std::string("Error transforming variable sigma: ") + e.what()), current_statement_begin__, prog_reader__());
        }
        params_r__ = writer__.data_r();
        params_i__ = writer__.data_i();
    }
    void transform_inits(const stan::io::var_context& context,
                         Eigen::Matrix<double, Eigen::Dynamic, 1>& params_r,
                         std::ostream* pstream__) const {
      std::vector<double> params_r_vec;
      std::vector<int> params_i_vec;
      transform_inits(context, params_i_vec, params_r_vec, pstream__);
      params_r.resize(params_r_vec.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r(i) = params_r_vec[i];
    }
    template <bool propto__, bool jacobian__, typename T__>
    T__ log_prob(std::vector<T__>& params_r__,
                 std::vector<int>& params_i__,
                 std::ostream* pstream__ = 0) const {
        typedef T__ local_scalar_t__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // dummy to suppress unused var warning
        T__ lp__(0.0);
        stan::math::accumulator<T__> lp_accum__;
        try {
            stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
            // model parameters
            current_statement_begin__ = 18;
            local_scalar_t__ theta_0;
            (void) theta_0;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_0 = in__.scalar_constrain(lp__);
            else
                theta_0 = in__.scalar_constrain();
            current_statement_begin__ = 19;
            local_scalar_t__ theta_1;
            (void) theta_1;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_1 = in__.scalar_constrain(lp__);
            else
                theta_1 = in__.scalar_constrain();
            current_statement_begin__ = 20;
            local_scalar_t__ theta_2_raw;
            (void) theta_2_raw;  // dummy to suppress unused var warning
            if (jacobian__)
                theta_2_raw = in__.scalar_lub_constrain(0, 1.5, lp__);
            else
                theta_2_raw = in__.scalar_lub_constrain(0, 1.5);
            current_statement_begin__ = 21;
            local_scalar_t__ sigma;
            (void) sigma;  // dummy to suppress unused var warning
            if (jacobian__)
                sigma = in__.scalar_lb_constrain(0, lp__);
            else
                sigma = in__.scalar_lb_constrain(0);
            // transformed parameters
            current_statement_begin__ = 25;
            validate_non_negative_index("resp_hat", "N_obs", N_obs);
            Eigen::Matrix<local_scalar_t__, Eigen::Dynamic, 1> resp_hat(N_obs);
            stan::math::initialize(resp_hat, DUMMY_VAR__);
            stan::math::fill(resp_hat, DUMMY_VAR__);
            current_statement_begin__ = 26;
            local_scalar_t__ theta_2;
            (void) theta_2;  // dummy to suppress unused var warning
            stan::math::initialize(theta_2, DUMMY_VAR__);
            stan::math::fill(theta_2, DUMMY_VAR__);
            // transformed parameters block statements
            current_statement_begin__ = 29;
            stan::math::assign(theta_2, (maxdose * theta_2_raw));
            current_statement_begin__ = 32;
            for (int i = 1; i <= N_obs; ++i) {
                current_statement_begin__ = 33;
                stan::model::assign(resp_hat, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (theta_0 + ((theta_1 * get_base1(dose, i, "dose", 1)) / (theta_2 + get_base1(dose, i, "dose", 1)))), 
                            "assigning variable resp_hat");
            }
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 25;
            size_t resp_hat_j_1_max__ = N_obs;
            for (size_t j_1__ = 0; j_1__ < resp_hat_j_1_max__; ++j_1__) {
                if (stan::math::is_uninitialized(resp_hat(j_1__))) {
                    std::stringstream msg__;
                    msg__ << "Undefined transformed parameter: resp_hat" << "(" << j_1__ << ")";
                    stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable resp_hat: ") + msg__.str()), current_statement_begin__, prog_reader__());
                }
            }
            current_statement_begin__ = 26;
            if (stan::math::is_uninitialized(theta_2)) {
                std::stringstream msg__;
                msg__ << "Undefined transformed parameter: theta_2";
                stan::lang::rethrow_located(std::runtime_error(std::string("Error initializing variable theta_2: ") + msg__.str()), current_statement_begin__, prog_reader__());
            }
            check_greater_or_equal(function__, "theta_2", theta_2, 0);
            // model body
            current_statement_begin__ = 40;
            lp_accum__.add(normal_log<propto__>(sigma, 0, prior_stdev_sigma));
            current_statement_begin__ = 41;
            lp_accum__.add(normal_log<propto__>(theta_0, 0, 100));
            current_statement_begin__ = 42;
            lp_accum__.add(normal_log<propto__>(theta_1, 0, 100));
            current_statement_begin__ = 43;
            lp_accum__.add(lognormal_log<propto__>(theta_2_raw, -(2.5), 1.8));
            current_statement_begin__ = 46;
            lp_accum__.add(normal_log<propto__>(resp, resp_hat, sigma));
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
        lp_accum__.add(lp__);
        return lp_accum__.sum();
    } // log_prob()
    template <bool propto, bool jacobian, typename T_>
    T_ log_prob(Eigen::Matrix<T_,Eigen::Dynamic,1>& params_r,
               std::ostream* pstream = 0) const {
      std::vector<T_> vec_params_r;
      vec_params_r.reserve(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        vec_params_r.push_back(params_r(i));
      std::vector<int> vec_params_i;
      return log_prob<propto,jacobian,T_>(vec_params_r, vec_params_i, pstream);
    }
    void get_param_names(std::vector<std::string>& names__) const {
        names__.resize(0);
        names__.push_back("theta_0");
        names__.push_back("theta_1");
        names__.push_back("theta_2_raw");
        names__.push_back("sigma");
        names__.push_back("resp_hat");
        names__.push_back("theta_2");
        names__.push_back("resp_pred_mean");
        names__.push_back("resp_pred");
        names__.push_back("log_lik");
        names__.push_back("theta_2_new");
    }
    void get_dims(std::vector<std::vector<size_t> >& dimss__) const {
        dimss__.resize(0);
        std::vector<size_t> dims__;
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_obs);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_pred);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_pred);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(N_obs);
        dimss__.push_back(dims__);
        dims__.resize(0);
        dims__.push_back(3);
        dimss__.push_back(dims__);
    }
    template <typename RNG>
    void write_array(RNG& base_rng__,
                     std::vector<double>& params_r__,
                     std::vector<int>& params_i__,
                     std::vector<double>& vars__,
                     bool include_tparams__ = true,
                     bool include_gqs__ = true,
                     std::ostream* pstream__ = 0) const {
        typedef double local_scalar_t__;
        vars__.resize(0);
        stan::io::reader<local_scalar_t__> in__(params_r__, params_i__);
        static const char* function__ = "model_Pooling_namespace::write_array";
        (void) function__;  // dummy to suppress unused var warning
        // read-transform, write parameters
        double theta_0 = in__.scalar_constrain();
        vars__.push_back(theta_0);
        double theta_1 = in__.scalar_constrain();
        vars__.push_back(theta_1);
        double theta_2_raw = in__.scalar_lub_constrain(0, 1.5);
        vars__.push_back(theta_2_raw);
        double sigma = in__.scalar_lb_constrain(0);
        vars__.push_back(sigma);
        double lp__ = 0.0;
        (void) lp__;  // dummy to suppress unused var warning
        stan::math::accumulator<double> lp_accum__;
        local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
        (void) DUMMY_VAR__;  // suppress unused var warning
        if (!include_tparams__ && !include_gqs__) return;
        try {
            // declare and define transformed parameters
            current_statement_begin__ = 25;
            validate_non_negative_index("resp_hat", "N_obs", N_obs);
            Eigen::Matrix<double, Eigen::Dynamic, 1> resp_hat(N_obs);
            stan::math::initialize(resp_hat, DUMMY_VAR__);
            stan::math::fill(resp_hat, DUMMY_VAR__);
            current_statement_begin__ = 26;
            double theta_2;
            (void) theta_2;  // dummy to suppress unused var warning
            stan::math::initialize(theta_2, DUMMY_VAR__);
            stan::math::fill(theta_2, DUMMY_VAR__);
            // do transformed parameters statements
            current_statement_begin__ = 29;
            stan::math::assign(theta_2, (maxdose * theta_2_raw));
            current_statement_begin__ = 32;
            for (int i = 1; i <= N_obs; ++i) {
                current_statement_begin__ = 33;
                stan::model::assign(resp_hat, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (theta_0 + ((theta_1 * get_base1(dose, i, "dose", 1)) / (theta_2 + get_base1(dose, i, "dose", 1)))), 
                            "assigning variable resp_hat");
            }
            if (!include_gqs__ && !include_tparams__) return;
            // validate transformed parameters
            const char* function__ = "validate transformed params";
            (void) function__;  // dummy to suppress unused var warning
            current_statement_begin__ = 26;
            check_greater_or_equal(function__, "theta_2", theta_2, 0);
            // write transformed parameters
            if (include_tparams__) {
                size_t resp_hat_j_1_max__ = N_obs;
                for (size_t j_1__ = 0; j_1__ < resp_hat_j_1_max__; ++j_1__) {
                    vars__.push_back(resp_hat(j_1__));
                }
                vars__.push_back(theta_2);
            }
            if (!include_gqs__) return;
            // declare and define generated quantities
            current_statement_begin__ = 52;
            validate_non_negative_index("resp_pred_mean", "N_pred", N_pred);
            Eigen::Matrix<double, Eigen::Dynamic, 1> resp_pred_mean(N_pred);
            stan::math::initialize(resp_pred_mean, DUMMY_VAR__);
            stan::math::fill(resp_pred_mean, DUMMY_VAR__);
            current_statement_begin__ = 53;
            validate_non_negative_index("resp_pred", "N_pred", N_pred);
            std::vector<double> resp_pred(N_pred, double(0));
            stan::math::initialize(resp_pred, DUMMY_VAR__);
            stan::math::fill(resp_pred, DUMMY_VAR__);
            current_statement_begin__ = 54;
            validate_non_negative_index("log_lik", "N_obs", N_obs);
            Eigen::Matrix<double, Eigen::Dynamic, 1> log_lik(N_obs);
            stan::math::initialize(log_lik, DUMMY_VAR__);
            stan::math::fill(log_lik, DUMMY_VAR__);
            current_statement_begin__ = 55;
            validate_non_negative_index("theta_2_new", "3", 3);
            std::vector<double> theta_2_new(3, double(0));
            stan::math::initialize(theta_2_new, DUMMY_VAR__);
            stan::math::fill(theta_2_new, DUMMY_VAR__);
            // generated quantities statements
            current_statement_begin__ = 58;
            stan::model::assign(theta_2_new, 
                        stan::model::cons_list(stan::model::index_uni(1), stan::model::nil_index_list()), 
                        (theta_2 / 2), 
                        "assigning variable theta_2_new");
            current_statement_begin__ = 59;
            stan::model::assign(theta_2_new, 
                        stan::model::cons_list(stan::model::index_uni(2), stan::model::nil_index_list()), 
                        theta_2, 
                        "assigning variable theta_2_new");
            current_statement_begin__ = 60;
            stan::model::assign(theta_2_new, 
                        stan::model::cons_list(stan::model::index_uni(3), stan::model::nil_index_list()), 
                        (theta_2 * 2), 
                        "assigning variable theta_2_new");
            current_statement_begin__ = 64;
            for (int i = 1; i <= N_pred; ++i) {
                current_statement_begin__ = 65;
                stan::model::assign(resp_pred_mean, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            (theta_0 + ((theta_1 * get_base1(Pred_doses, i, "Pred_doses", 1)) / (theta_2 + get_base1(Pred_doses, i, "Pred_doses", 1)))), 
                            "assigning variable resp_pred_mean");
                current_statement_begin__ = 66;
                stan::model::assign(resp_pred, 
                            stan::model::cons_list(stan::model::index_uni(i), stan::model::nil_index_list()), 
                            normal_rng(get_base1(resp_pred_mean, i, "resp_pred_mean", 1), sigma, base_rng__), 
                            "assigning variable resp_pred");
            }
            current_statement_begin__ = 71;
            for (int n = 1; n <= N_obs; ++n) {
                current_statement_begin__ = 72;
                stan::model::assign(log_lik, 
                            stan::model::cons_list(stan::model::index_uni(n), stan::model::nil_index_list()), 
                            normal_log(get_base1(resp, n, "resp", 1), get_base1(resp_hat, n, "resp_hat", 1), sigma), 
                            "assigning variable log_lik");
            }
            // validate, write generated quantities
            current_statement_begin__ = 52;
            size_t resp_pred_mean_j_1_max__ = N_pred;
            for (size_t j_1__ = 0; j_1__ < resp_pred_mean_j_1_max__; ++j_1__) {
                vars__.push_back(resp_pred_mean(j_1__));
            }
            current_statement_begin__ = 53;
            size_t resp_pred_k_0_max__ = N_pred;
            for (size_t k_0__ = 0; k_0__ < resp_pred_k_0_max__; ++k_0__) {
                vars__.push_back(resp_pred[k_0__]);
            }
            current_statement_begin__ = 54;
            size_t log_lik_j_1_max__ = N_obs;
            for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
                vars__.push_back(log_lik(j_1__));
            }
            current_statement_begin__ = 55;
            size_t theta_2_new_i_0_max__ = 3;
            for (size_t i_0__ = 0; i_0__ < theta_2_new_i_0_max__; ++i_0__) {
                check_greater_or_equal(function__, "theta_2_new[i_0__]", theta_2_new[i_0__], 0);
            }
            size_t theta_2_new_k_0_max__ = 3;
            for (size_t k_0__ = 0; k_0__ < theta_2_new_k_0_max__; ++k_0__) {
                vars__.push_back(theta_2_new[k_0__]);
            }
        } catch (const std::exception& e) {
            stan::lang::rethrow_located(e, current_statement_begin__, prog_reader__());
            // Next line prevents compiler griping about no return
            throw std::runtime_error("*** IF YOU SEE THIS, PLEASE REPORT A BUG ***");
        }
    }
    template <typename RNG>
    void write_array(RNG& base_rng,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& params_r,
                     Eigen::Matrix<double,Eigen::Dynamic,1>& vars,
                     bool include_tparams = true,
                     bool include_gqs = true,
                     std::ostream* pstream = 0) const {
      std::vector<double> params_r_vec(params_r.size());
      for (int i = 0; i < params_r.size(); ++i)
        params_r_vec[i] = params_r(i);
      std::vector<double> vars_vec;
      std::vector<int> params_i_vec;
      write_array(base_rng, params_r_vec, params_i_vec, vars_vec, include_tparams, include_gqs, pstream);
      vars.resize(vars_vec.size());
      for (int i = 0; i < vars.size(); ++i)
        vars(i) = vars_vec[i];
    }
    static std::string model_name() {
        return "model_Pooling";
    }
    void constrained_param_names(std::vector<std::string>& param_names__,
                                 bool include_tparams__ = true,
                                 bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_2_raw";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t resp_hat_j_1_max__ = N_obs;
            for (size_t j_1__ = 0; j_1__ < resp_hat_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "resp_hat" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_2";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t resp_pred_mean_j_1_max__ = N_pred;
        for (size_t j_1__ = 0; j_1__ < resp_pred_mean_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "resp_pred_mean" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t resp_pred_k_0_max__ = N_pred;
        for (size_t k_0__ = 0; k_0__ < resp_pred_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "resp_pred" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = N_obs;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t theta_2_new_k_0_max__ = 3;
        for (size_t k_0__ = 0; k_0__ < theta_2_new_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_2_new" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
    void unconstrained_param_names(std::vector<std::string>& param_names__,
                                   bool include_tparams__ = true,
                                   bool include_gqs__ = true) const {
        std::stringstream param_name_stream__;
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_0";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_1";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "theta_2_raw";
        param_names__.push_back(param_name_stream__.str());
        param_name_stream__.str(std::string());
        param_name_stream__ << "sigma";
        param_names__.push_back(param_name_stream__.str());
        if (!include_gqs__ && !include_tparams__) return;
        if (include_tparams__) {
            size_t resp_hat_j_1_max__ = N_obs;
            for (size_t j_1__ = 0; j_1__ < resp_hat_j_1_max__; ++j_1__) {
                param_name_stream__.str(std::string());
                param_name_stream__ << "resp_hat" << '.' << j_1__ + 1;
                param_names__.push_back(param_name_stream__.str());
            }
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_2";
            param_names__.push_back(param_name_stream__.str());
        }
        if (!include_gqs__) return;
        size_t resp_pred_mean_j_1_max__ = N_pred;
        for (size_t j_1__ = 0; j_1__ < resp_pred_mean_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "resp_pred_mean" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t resp_pred_k_0_max__ = N_pred;
        for (size_t k_0__ = 0; k_0__ < resp_pred_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "resp_pred" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t log_lik_j_1_max__ = N_obs;
        for (size_t j_1__ = 0; j_1__ < log_lik_j_1_max__; ++j_1__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "log_lik" << '.' << j_1__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
        size_t theta_2_new_k_0_max__ = 3;
        for (size_t k_0__ = 0; k_0__ < theta_2_new_k_0_max__; ++k_0__) {
            param_name_stream__.str(std::string());
            param_name_stream__ << "theta_2_new" << '.' << k_0__ + 1;
            param_names__.push_back(param_name_stream__.str());
        }
    }
}; // model
}  // namespace
typedef model_Pooling_namespace::model_Pooling stan_model;
#endif
